name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  IMAGE_FAKE_KUBELET: fake-kubelet:test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: wzshiming/fake-kubelet
      - name: Build image
        run: |
          docker build -t "${IMAGE_FAKE_KUBELET}" .
          docker save "${IMAGE_FAKE_KUBELET}" -o image.tar
      - name: Upload image tar
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: image.tar

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Download for image tar
        uses: actions/download-artifact@v2
        with:
          name: test
      - name: Load image tar
        run: |
          docker load -i image.tar
      - name: Run test
        run: ./fake-k8s.test.sh

  mock-test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Download for image tar
        uses: actions/download-artifact@v2
        with:
          name: test
      - name: Load image tar
        run: |
          docker load -i image.tar
      - name: Run mock test
        run: ./fake-k8s.mock.test.sh

  benchmark-test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Download for image tar
        uses: actions/download-artifact@v2
        with:
          name: test
      - name: Load image tar
        run: |
          docker load -i image.tar
      - name: Run benchmark test
        run: ./fake-k8s.benchmark.test.sh
